// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: db/item_property.proto

package db

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SortableProperty is used to reference a sortable (i.e. locally indexed)
// property within an item. These properties are either built in, or they must
// be explicitly declared in the schema / store config so they can be populated
// when items are written/updated.
type SortableProperty int32

const (
	// SORTABLE_PROPERTY_KEY_PATH is the full key path of the item. This is the
	// default sort property if none is specified. TODO: Document how these are ordered.
	SortableProperty_SORTABLE_PROPERTY_KEY_PATH SortableProperty = 0
	// SORTABLE_PROPERTY_LAST_MODIFIED_VERSION sorts by the last modified version
	// of the items, with ascending order being from oldest to newest. This is
	// only available if the store / item is configured to track last modified
	// versions.
	SortableProperty_SORTABLE_PROPERTY_LAST_MODIFIED_VERSION SortableProperty = 1
	// SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_1 through
	// SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_4 are user-specified sortable
	// properties which may be defined in the schema. The maximum supported number
	// of group local indexes currently depends on the store configuration and the
	// underlying database platform.
	SortableProperty_SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_1 SortableProperty = 8
	SortableProperty_SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_2 SortableProperty = 9
	SortableProperty_SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_3 SortableProperty = 10
	SortableProperty_SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_4 SortableProperty = 11
)

// Enum value maps for SortableProperty.
var (
	SortableProperty_name = map[int32]string{
		0:  "SORTABLE_PROPERTY_KEY_PATH",
		1:  "SORTABLE_PROPERTY_LAST_MODIFIED_VERSION",
		8:  "SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_1",
		9:  "SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_2",
		10: "SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_3",
		11: "SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_4",
	}
	SortableProperty_value = map[string]int32{
		"SORTABLE_PROPERTY_KEY_PATH":              0,
		"SORTABLE_PROPERTY_LAST_MODIFIED_VERSION": 1,
		"SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_1":   8,
		"SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_2":   9,
		"SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_3":   10,
		"SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_4":   11,
	}
)

func (x SortableProperty) Enum() *SortableProperty {
	p := new(SortableProperty)
	*p = x
	return p
}

func (x SortableProperty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortableProperty) Descriptor() protoreflect.EnumDescriptor {
	return file_db_item_property_proto_enumTypes[0].Descriptor()
}

func (SortableProperty) Type() protoreflect.EnumType {
	return &file_db_item_property_proto_enumTypes[0]
}

func (x SortableProperty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortableProperty.Descriptor instead.
func (SortableProperty) EnumDescriptor() ([]byte, []int) {
	return file_db_item_property_proto_rawDescGZIP(), []int{0}
}

var File_db_item_property_proto protoreflect.FileDescriptor

const file_db_item_property_proto_rawDesc = "" +
	"\n" +
	"\x16db/item_property.proto\x12\n" +
	"stately.db*\x8b\x02\n" +
	"\x10SortableProperty\x12\x1e\n" +
	"\x1aSORTABLE_PROPERTY_KEY_PATH\x10\x00\x12+\n" +
	"'SORTABLE_PROPERTY_LAST_MODIFIED_VERSION\x10\x01\x12)\n" +
	"%SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_1\x10\b\x12)\n" +
	"%SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_2\x10\t\x12)\n" +
	"%SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_3\x10\n" +
	"\x12)\n" +
	"%SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_4\x10\vB\x92\x01\n" +
	"\x0ecom.stately.dbB\x11ItemPropertyProtoP\x01Z$github.com/StatelyCloud/go-sdk/pb/db\xa2\x02\x03SDX\xaa\x02\n" +
	"Stately.Db\xca\x02\n" +
	"Stately\\Db\xe2\x02\x16Stately\\Db\\GPBMetadata\xea\x02\vStately::Dbb\x06proto3"

var (
	file_db_item_property_proto_rawDescOnce sync.Once
	file_db_item_property_proto_rawDescData []byte
)

func file_db_item_property_proto_rawDescGZIP() []byte {
	file_db_item_property_proto_rawDescOnce.Do(func() {
		file_db_item_property_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_item_property_proto_rawDesc), len(file_db_item_property_proto_rawDesc)))
	})
	return file_db_item_property_proto_rawDescData
}

var file_db_item_property_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_db_item_property_proto_goTypes = []any{
	(SortableProperty)(0), // 0: stately.db.SortableProperty
}
var file_db_item_property_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_item_property_proto_init() }
func file_db_item_property_proto_init() {
	if File_db_item_property_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_item_property_proto_rawDesc), len(file_db_item_property_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_item_property_proto_goTypes,
		DependencyIndexes: file_db_item_property_proto_depIdxs,
		EnumInfos:         file_db_item_property_proto_enumTypes,
	}.Build()
	File_db_item_property_proto = out.File
	file_db_item_property_proto_goTypes = nil
	file_db_item_property_proto_depIdxs = nil
}
