// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: db/list_token.proto

package db

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListToken is an opaque token that can be used to continue (paginate) or sync
// results from a previous List operation.
type ListToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// token_data will always be returned, and can be used to expand the result
	// set via ContinueList (if can_continue is true), or to get changed items
	// within the result set via SyncList (if can_sync is true). The token_data
	// itself is opaque and cannot be parsed or modified by clients.
	TokenData []byte `protobuf:"bytes,1,opt,name=token_data,json=tokenData,proto3" json:"token_data,omitempty"`
	// can_continue indicates that there are more results available by expanding
	// the pagination window by calling ContinueList with this token.
	CanContinue bool `protobuf:"varint,2,opt,name=can_continue,json=canContinue,proto3" json:"can_continue,omitempty"`
	// can_sync indicates that you could call SyncList with this token later to
	// get updated items. This is determined by the type of store you're listing
	// from.
	CanSync bool `protobuf:"varint,3,opt,name=can_sync,json=canSync,proto3" json:"can_sync,omitempty"`
}

func (x *ListToken) Reset() {
	*x = ListToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_list_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToken) ProtoMessage() {}

func (x *ListToken) ProtoReflect() protoreflect.Message {
	mi := &file_db_list_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToken.ProtoReflect.Descriptor instead.
func (*ListToken) Descriptor() ([]byte, []int) {
	return file_db_list_token_proto_rawDescGZIP(), []int{0}
}

func (x *ListToken) GetTokenData() []byte {
	if x != nil {
		return x.TokenData
	}
	return nil
}

func (x *ListToken) GetCanContinue() bool {
	if x != nil {
		return x.CanContinue
	}
	return false
}

func (x *ListToken) GetCanSync() bool {
	if x != nil {
		return x.CanSync
	}
	return false
}

var File_db_list_token_proto protoreflect.FileDescriptor

var file_db_list_token_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x62, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6c, 0x79, 0x2e, 0x64,
	0x62, 0x22, 0x70, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x25,
	0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x61, 0x6e,
	0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x61, 0x6e, 0x5f,
	0x73, 0x79, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x53,
	0x79, 0x6e, 0x63, 0x42, 0x8f, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x6c, 0x79, 0x2e, 0x64, 0x62, 0x42, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6c, 0x79, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x62, 0xa2, 0x02,
	0x03, 0x53, 0x44, 0x58, 0xaa, 0x02, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6c, 0x79, 0x2e, 0x44,
	0x62, 0xca, 0x02, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6c, 0x79, 0x5c, 0x44, 0x62, 0xe2, 0x02,
	0x16, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6c, 0x79, 0x5c, 0x44, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6c,
	0x79, 0x3a, 0x3a, 0x44, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_list_token_proto_rawDescOnce sync.Once
	file_db_list_token_proto_rawDescData = file_db_list_token_proto_rawDesc
)

func file_db_list_token_proto_rawDescGZIP() []byte {
	file_db_list_token_proto_rawDescOnce.Do(func() {
		file_db_list_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_list_token_proto_rawDescData)
	})
	return file_db_list_token_proto_rawDescData
}

var file_db_list_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_db_list_token_proto_goTypes = []interface{}{
	(*ListToken)(nil), // 0: stately.db.ListToken
}
var file_db_list_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_list_token_proto_init() }
func file_db_list_token_proto_init() {
	if File_db_list_token_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_list_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_list_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_list_token_proto_goTypes,
		DependencyIndexes: file_db_list_token_proto_depIdxs,
		MessageInfos:      file_db_list_token_proto_msgTypes,
	}.Build()
	File_db_list_token_proto = out.File
	file_db_list_token_proto_rawDesc = nil
	file_db_list_token_proto_goTypes = nil
	file_db_list_token_proto_depIdxs = nil
}
