// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: db/list_filters.proto

package db

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FilterCondition_ItemType
	Value         isFilterCondition_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterCondition) Reset() {
	*x = FilterCondition{}
	mi := &file_db_list_filters_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCondition) ProtoMessage() {}

func (x *FilterCondition) ProtoReflect() protoreflect.Message {
	mi := &file_db_list_filters_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCondition.ProtoReflect.Descriptor instead.
func (*FilterCondition) Descriptor() ([]byte, []int) {
	return file_db_list_filters_proto_rawDescGZIP(), []int{0}
}

func (x *FilterCondition) GetValue() isFilterCondition_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FilterCondition) GetItemType() string {
	if x != nil {
		if x, ok := x.Value.(*FilterCondition_ItemType); ok {
			return x.ItemType
		}
	}
	return ""
}

type isFilterCondition_Value interface {
	isFilterCondition_Value()
}

type FilterCondition_ItemType struct {
	// item_type is the type of item to filter by.
	ItemType string `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3,oneof"`
}

func (*FilterCondition_ItemType) isFilterCondition_Value() {}

var File_db_list_filters_proto protoreflect.FileDescriptor

const file_db_list_filters_proto_rawDesc = "" +
	"\n" +
	"\x15db/list_filters.proto\x12\n" +
	"stately.db\x1a\x1bbuf/validate/validate.proto\"@\n" +
	"\x0fFilterCondition\x12\x1d\n" +
	"\titem_type\x18\x01 \x01(\tH\x00R\bitemTypeB\x0e\n" +
	"\x05value\x12\x05\xbaH\x02\b\x01B\x91\x01\n" +
	"\x0ecom.stately.dbB\x10ListFiltersProtoP\x01Z$github.com/StatelyCloud/go-sdk/pb/db\xa2\x02\x03SDX\xaa\x02\n" +
	"Stately.Db\xca\x02\n" +
	"Stately\\Db\xe2\x02\x16Stately\\Db\\GPBMetadata\xea\x02\vStately::Dbb\x06proto3"

var (
	file_db_list_filters_proto_rawDescOnce sync.Once
	file_db_list_filters_proto_rawDescData []byte
)

func file_db_list_filters_proto_rawDescGZIP() []byte {
	file_db_list_filters_proto_rawDescOnce.Do(func() {
		file_db_list_filters_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_list_filters_proto_rawDesc), len(file_db_list_filters_proto_rawDesc)))
	})
	return file_db_list_filters_proto_rawDescData
}

var file_db_list_filters_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_db_list_filters_proto_goTypes = []any{
	(*FilterCondition)(nil), // 0: stately.db.FilterCondition
}
var file_db_list_filters_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_list_filters_proto_init() }
func file_db_list_filters_proto_init() {
	if File_db_list_filters_proto != nil {
		return
	}
	file_db_list_filters_proto_msgTypes[0].OneofWrappers = []any{
		(*FilterCondition_ItemType)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_list_filters_proto_rawDesc), len(file_db_list_filters_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_list_filters_proto_goTypes,
		DependencyIndexes: file_db_list_filters_proto_depIdxs,
		MessageInfos:      file_db_list_filters_proto_msgTypes,
	}.Build()
	File_db_list_filters_proto = out.File
	file_db_list_filters_proto_goTypes = nil
	file_db_list_filters_proto_depIdxs = nil
}
