// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: dbmanagement/list-stores.proto

package dbmanagement

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListStoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// project_id is the project within which we will list all known stores.
	// Project ID is a globally unique ID tied to a project. We assume the ID will
	// be available from the CLI or console, which will know it from having logged
	// in / selected an active project.
	ProjectId uint64 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *ListStoresRequest) Reset() {
	*x = ListStoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbmanagement_list_stores_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresRequest) ProtoMessage() {}

func (x *ListStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbmanagement_list_stores_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresRequest.ProtoReflect.Descriptor instead.
func (*ListStoresRequest) Descriptor() ([]byte, []int) {
	return file_dbmanagement_list_stores_proto_rawDescGZIP(), []int{0}
}

func (x *ListStoresRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type ListStoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// stores is a list of all stores in the project that this user can view. The
	// user can subsequently call DescribeStore to get more info about an
	// individual store.
	Stores []*ListStoresEntry `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
}

func (x *ListStoresResponse) Reset() {
	*x = ListStoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbmanagement_list_stores_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresResponse) ProtoMessage() {}

func (x *ListStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbmanagement_list_stores_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresResponse.ProtoReflect.Descriptor instead.
func (*ListStoresResponse) Descriptor() ([]byte, []int) {
	return file_dbmanagement_list_stores_proto_rawDescGZIP(), []int{1}
}

func (x *ListStoresResponse) GetStores() []*ListStoresEntry {
	if x != nil {
		return x.Stores
	}
	return nil
}

// ListStoresEntry provides just enough information about a store to show it in
// a list. It's effectively Pick<StoreInfo, 'store_id' | 'name' |
// 'description'>. However it's possible that this should just be StoreInfo if
// StoreInfo isn't going to ever be very complicated.
type ListStoresEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// store_id is a globally unique identifier for a store. Users will of course
	// be able to name their stores with friendly names, but for efficiency's sake
	// the API talks in terms of IDs, which the user can find in the console or
	// via a DescribeStore command. Store IDs are assigned by the system when a
	// store is created.
	StoreId uint64 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// name is a user-facing, memorable name for the store. While most APIs deal
	// strictly in store IDs, the name will be shown in the console and usable
	// within the API.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// description is a longer-form, user-facing explanation of what the store is
	// used for - it is used in the console and in generated documentation. We
	// should encourage users to provide a meaningful description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ListStoresEntry) Reset() {
	*x = ListStoresEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbmanagement_list_stores_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStoresEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresEntry) ProtoMessage() {}

func (x *ListStoresEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dbmanagement_list_stores_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresEntry.ProtoReflect.Descriptor instead.
func (*ListStoresEntry) Descriptor() ([]byte, []int) {
	return file_dbmanagement_list_stores_proto_rawDescGZIP(), []int{2}
}

func (x *ListStoresEntry) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *ListStoresEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListStoresEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_dbmanagement_list_stores_proto protoreflect.FileDescriptor

var file_dbmanagement_list_stores_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x64, 0x62, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x6c,
	0x69, 0x73, 0x74, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6c, 0x79, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42,
	0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x22, 0x46, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x6c, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x06, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x21,
	0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x20, 0x01, 0x28, 0x40, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2b, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xba, 0x48, 0x06, 0x72, 0x04, 0x28, 0x80, 0x80, 0x01,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dbmanagement_list_stores_proto_rawDescOnce sync.Once
	file_dbmanagement_list_stores_proto_rawDescData = file_dbmanagement_list_stores_proto_rawDesc
)

func file_dbmanagement_list_stores_proto_rawDescGZIP() []byte {
	file_dbmanagement_list_stores_proto_rawDescOnce.Do(func() {
		file_dbmanagement_list_stores_proto_rawDescData = protoimpl.X.CompressGZIP(file_dbmanagement_list_stores_proto_rawDescData)
	})
	return file_dbmanagement_list_stores_proto_rawDescData
}

var file_dbmanagement_list_stores_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dbmanagement_list_stores_proto_goTypes = []interface{}{
	(*ListStoresRequest)(nil),  // 0: stately.ListStoresRequest
	(*ListStoresResponse)(nil), // 1: stately.ListStoresResponse
	(*ListStoresEntry)(nil),    // 2: stately.ListStoresEntry
}
var file_dbmanagement_list_stores_proto_depIdxs = []int32{
	2, // 0: stately.ListStoresResponse.stores:type_name -> stately.ListStoresEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dbmanagement_list_stores_proto_init() }
func file_dbmanagement_list_stores_proto_init() {
	if File_dbmanagement_list_stores_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dbmanagement_list_stores_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbmanagement_list_stores_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbmanagement_list_stores_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStoresEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dbmanagement_list_stores_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dbmanagement_list_stores_proto_goTypes,
		DependencyIndexes: file_dbmanagement_list_stores_proto_depIdxs,
		MessageInfos:      file_dbmanagement_list_stores_proto_msgTypes,
	}.Build()
	File_dbmanagement_list_stores_proto = out.File
	file_dbmanagement_list_stores_proto_rawDesc = nil
	file_dbmanagement_list_stores_proto_goTypes = nil
	file_dbmanagement_list_stores_proto_depIdxs = nil
}
